import type { TourProduct } from './types';

// Maps sheet column index (0-based) to TourProduct field name
// 70 columns total (A=0 through BR=69)
export const COLUMN_MAP: Record<number, keyof Omit<TourProduct, 'rowIndex'>> = {
  0: 'country',
  1: 'city',
  2: 'department',
  3: 'region',
  4: 'productType',
  5: 'link',
  6: 'duration',
  7: 'productStatus',
  8: 'productName',
  9: 'written',
  10: 'notes',
  11: 'isOk',
  12: 'ssOk',
  13: 'imageLinks',
  14: 'maxPax',
  15: 'guide',
  16: 'driver',
  17: 'driverGuide',
  18: 'guideWhere',
  19: 'componentsOfTour',
  20: 'attractionIncluded',
  21: 'attractionOptional',
  22: 'transportation',
  23: 'attractionsIncluded',
  24: 'attractionLink',
  25: 'providerPrice',
  26: 'providerUrl',
  27: 'centralProviderLinks',
  28: 'centralTransportLinks',
  29: 'transportationPrice',
  30: 'vatYN',
  31: 'vatPercent',
  32: 'totalBuyingPrice',
  33: 'cancellation',
  34: 'pic',
  35: 'b2bPriceInstant',
  36: 'b2bPriceOnRequest',
  37: 'b2cPriceInstant',
  38: 'b2cPriceOnRequest',
  39: 'extraHrB2BInstant',
  40: 'extraHrB2BRequest',
  41: 'extraHrB2CInstant',
  42: 'extraHrB2CRequest',
  43: 'tourValidityGeneral',
  44: 'tourValiditySpecific',
  45: 'cancelInstant',
  46: 'cutoffInstant',
  47: 'cancelOnRequest',
  48: 'cutoffOnRequest',
  49: 'notesGeneral',
  50: 'otaMasterSheet',
  51: 'otaTravmonde',
  52: 'otaBookableTours',
  53: 'otaViator',
  54: 'otaGyg',
  55: 'otaHotelbeds',
  56: 'otaProjectExpedition',
  57: 'otaAirbnb',
  58: 'otaBokun',
  59: 'otaTrekksoft',
  60: 'otaTuiMusement',
  61: 'otaKlook',
  62: 'otaToristy',
  63: 'otaTourHQ',
  64: 'qualityRemarks',
  65: 'readyForUpload',
  66: 'uploadedPic',
  67: 'dateOfDispatch',
  68: 'dateUploaded',
  69: 'productLink',
};

// Reverse: field name → column index
export const FIELD_TO_COL: Record<keyof Omit<TourProduct, 'rowIndex'>, number> =
  Object.fromEntries(
    Object.entries(COLUMN_MAP).map(([col, field]) => [field, Number(col)])
  ) as Record<keyof Omit<TourProduct, 'rowIndex'>, number>;

// Sheet column headers (as they appear in row 1)
export const COLUMN_HEADERS: Record<number, string> = {
  0: 'Country',
  1: 'City',
  2: 'Department',
  3: 'Region',
  4: 'Product type',
  5: 'Link',
  6: '🕐',
  7: 'Product Status',
  8: 'Product Name',
  9: 'Written',
  10: 'Notes',
  11: 'IS OK',
  12: 'SS OK',
  13: 'Image links',
  14: 'Max Pax',
  15: 'Guide',
  16: 'Driver',
  17: 'Driver-guide',
  18: 'Guide where',
  19: 'Components of tour',
  20: 'Attraction Included?',
  21: 'Attraction optional',
  22: 'Transportation',
  23: 'Attractions Included',
  24: 'Attraction Link',
  25: 'Provider Price',
  26: 'Provider URL',
  27: 'Central Provider Links',
  28: 'Central Transport Links',
  29: 'Transportation Price',
  30: 'VAT (Y/N)',
  31: 'VAT %',
  32: 'Total Buying Price',
  33: 'Cancellation',
  34: 'PIC',
  35: 'B2B Price (Instant)',
  36: 'B2B Price (On request)',
  37: 'B2C Price (Instant)',
  38: 'B2C Price (On request)',
  39: 'Extra Hr Suppl. B2B Instant',
  40: 'Ex. Hr B2B Request',
  41: 'Extra Hr B2C Instant',
  42: 'Extra Hr B2C Request',
  43: 'Tour Validity (General)',
  44: 'Tour Validity (Specific)',
  45: 'Cancel. INSTANT',
  46: 'Cut-off INSTANT',
  47: 'Cancel. On request',
  48: 'Cut-off On request',
  49: 'NOTES',
  50: 'OTA Master Sheet',
  51: 'Travmonde',
  52: 'Bookable Tours',
  53: 'Viator',
  54: 'GYG',
  55: 'Hotelbeds',
  56: 'Project Expedition',
  57: 'Airbnb',
  58: 'Bokun',
  59: 'Trekksoft',
  60: 'TUI/Musement',
  61: 'Klook',
  62: 'Toristy',
  63: 'TourHQ',
  64: 'Quality - Remarks',
  65: 'Ready for Upload',
  66: 'Uploaded (PIC)',
  67: 'Date of Dispatch',
  68: 'Date uploaded',
  69: 'Product link',
};

// Boolean fields (cols that store TRUE/FALSE or 1.0/0.0)
export const BOOLEAN_FIELDS = new Set<keyof TourProduct>([
  'written', 'ssOk', 'guide', 'driver', 'driverGuide',
  'attractionIncluded', 'attractionOptional', 'readyForUpload',
]);

// Fields where the raw cell value is a float/number
export const NUMBER_FIELDS = new Set<keyof TourProduct>(['vatPercent']);

// Product status values
export const PRODUCT_STATUSES = [
  'In Progress',
  'Completed',
  'In Progress - High priority',
  'On hold',
  'Ignored',
] as const;

// PIC values
export const PIC_VALUES = ['CM', 'LG', 'DS', 'CC', 'DV', 'SB', 'IS', 'Hanieh', 'RB'] as const;

// Column group definitions for the table UI
export const COLUMN_GROUPS = [
  {
    id: 'location',
    label: 'Location & Identity',
    fields: ['country', 'city', 'department', 'region', 'productType'] as const,
  },
  {
    id: 'product',
    label: 'Product Info',
    fields: ['link', 'duration', 'productStatus', 'productName', 'written', 'notes'] as const,
  },
  {
    id: 'content',
    label: 'Content Status',
    fields: ['isOk', 'ssOk', 'imageLinks'] as const,
  },
  {
    id: 'tour',
    label: 'Tour Configuration',
    fields: [
      'maxPax', 'guide', 'driver', 'driverGuide', 'guideWhere',
      'componentsOfTour', 'attractionIncluded', 'attractionOptional',
      'transportation', 'attractionsIncluded', 'attractionLink',
    ] as const,
  },
  {
    id: 'provider',
    label: 'Provider & Buying',
    fields: [
      'providerPrice', 'providerUrl', 'centralProviderLinks', 'centralTransportLinks',
      'transportationPrice', 'vatYN', 'vatPercent', 'totalBuyingPrice', 'cancellation',
    ] as const,
  },
  {
    id: 'assignment',
    label: 'Assignment',
    fields: ['pic'] as const,
  },
  {
    id: 'selling',
    label: 'Selling Prices',
    fields: [
      'b2bPriceInstant', 'b2bPriceOnRequest', 'b2cPriceInstant', 'b2cPriceOnRequest',
      'extraHrB2BInstant', 'extraHrB2BRequest', 'extraHrB2CInstant', 'extraHrB2CRequest',
    ] as const,
  },
  {
    id: 'validity',
    label: 'Validity & Cancellation',
    fields: [
      'tourValidityGeneral', 'tourValiditySpecific',
      'cancelInstant', 'cutoffInstant', 'cancelOnRequest', 'cutoffOnRequest',
    ] as const,
  },
  {
    id: 'notes',
    label: 'Notes & OTA Master',
    fields: ['notesGeneral', 'otaMasterSheet'] as const,
  },
  {
    id: 'ota',
    label: 'OTA Distribution',
    fields: [
      'otaTravmonde', 'otaBookableTours', 'otaViator', 'otaGyg', 'otaHotelbeds',
      'otaProjectExpedition', 'otaAirbnb', 'otaBokun', 'otaTrekksoft',
      'otaTuiMusement', 'otaKlook', 'otaToristy', 'otaTourHQ',
    ] as const,
  },
  {
    id: 'upload',
    label: 'Upload Workflow',
    fields: [
      'qualityRemarks', 'readyForUpload', 'uploadedPic',
      'dateOfDispatch', 'dateUploaded', 'productLink',
    ] as const,
  },
] as const;

// View presets (column visibility)
export const VIEW_PRESETS: Record<string, Array<keyof Omit<TourProduct, 'rowIndex'>>> = {
  overview: ['country', 'city', 'productType', 'link', 'duration', 'productStatus', 'pic', 'readyForUpload'],
  pricing: ['country', 'city', 'link', 'providerPrice', 'totalBuyingPrice', 'b2bPriceInstant', 'b2bPriceOnRequest', 'b2cPriceInstant', 'b2cPriceOnRequest', 'extraHrB2BInstant', 'extraHrB2BRequest', 'extraHrB2CInstant', 'extraHrB2CRequest'],
  ota: ['country', 'city', 'link', 'otaTravmonde', 'otaBookableTours', 'otaViator', 'otaGyg', 'otaHotelbeds', 'otaProjectExpedition', 'otaAirbnb', 'otaBokun', 'otaTrekksoft', 'otaTuiMusement', 'otaKlook', 'otaToristy', 'otaTourHQ'],
  upload: ['country', 'city', 'link', 'isOk', 'ssOk', 'qualityRemarks', 'readyForUpload', 'uploadedPic', 'dateOfDispatch', 'dateUploaded', 'productLink'],
  tourDetails: ['country', 'city', 'link', 'maxPax', 'guide', 'driver', 'driverGuide', 'componentsOfTour', 'attractionIncluded', 'attractionOptional', 'transportation', 'attractionsIncluded', 'attractionLink'],
};

// Status badge colours (Tailwind classes)
export const STATUS_COLORS: Record<string, { bg: string; text: string }> = {
  'In Progress': { bg: 'bg-amber-100', text: 'text-amber-800' },
  'Completed': { bg: 'bg-green-100', text: 'text-green-800' },
  'In Progress - High priority': { bg: 'bg-red-100', text: 'text-red-800' },
  'On hold': { bg: 'bg-gray-100', text: 'text-gray-600' },
  'Ignored': { bg: 'bg-gray-50', text: 'text-gray-400' },
};

// Human-readable display names for each field
export const FIELD_LABELS: Record<keyof Omit<TourProduct, 'rowIndex'>, string> = {
  country: 'Country',
  city: 'City',
  department: 'Department',
  region: 'Region',
  productType: 'Product Type',
  link: 'Link / Title',
  duration: 'Duration',
  productStatus: 'Status',
  productName: 'Product Name',
  written: 'Written',
  notes: 'Notes',
  isOk: 'IS OK',
  ssOk: 'SS OK',
  imageLinks: 'Image Links',
  maxPax: 'Max Pax',
  guide: 'Guide',
  driver: 'Driver',
  driverGuide: 'Driver-Guide',
  guideWhere: 'Guide Where',
  componentsOfTour: 'Components',
  attractionIncluded: 'Attraction Included?',
  attractionOptional: 'Attraction Optional',
  transportation: 'Transportation',
  attractionsIncluded: 'Attractions Included',
  attractionLink: 'Attraction Link',
  providerPrice: 'Provider Price',
  providerUrl: 'Provider URL',
  centralProviderLinks: 'Central Provider Links',
  centralTransportLinks: 'Central Transport Links',
  transportationPrice: 'Transport Price',
  vatYN: 'VAT (Y/N)',
  vatPercent: 'VAT %',
  totalBuyingPrice: 'Total Buying Price',
  cancellation: 'Cancellation',
  pic: 'PIC',
  b2bPriceInstant: 'B2B Instant',
  b2bPriceOnRequest: 'B2B On Request',
  b2cPriceInstant: 'B2C Instant',
  b2cPriceOnRequest: 'B2C On Request',
  extraHrB2BInstant: 'Extra Hr B2B Instant',
  extraHrB2BRequest: 'Extra Hr B2B Request',
  extraHrB2CInstant: 'Extra Hr B2C Instant',
  extraHrB2CRequest: 'Extra Hr B2C Request',
  tourValidityGeneral: 'Validity (General)',
  tourValiditySpecific: 'Validity (Specific)',
  cancelInstant: 'Cancel Instant',
  cutoffInstant: 'Cutoff Instant',
  cancelOnRequest: 'Cancel On Request',
  cutoffOnRequest: 'Cutoff On Request',
  notesGeneral: 'Notes (General)',
  otaMasterSheet: 'OTA Master Sheet',
  otaTravmonde: 'Travmonde',
  otaBookableTours: 'Bookable Tours',
  otaViator: 'Viator',
  otaGyg: 'GYG',
  otaHotelbeds: 'Hotelbeds',
  otaProjectExpedition: 'Project Expedition',
  otaAirbnb: 'Airbnb',
  otaBokun: 'Bokun',
  otaTrekksoft: 'Trekksoft',
  otaTuiMusement: 'TUI/Musement',
  otaKlook: 'Klook',
  otaToristy: 'Toristy',
  otaTourHQ: 'TourHQ',
  qualityRemarks: 'Quality Remarks',
  readyForUpload: 'Ready for Upload',
  uploadedPic: 'Uploaded (PIC)',
  dateOfDispatch: 'Date of Dispatch',
  dateUploaded: 'Date Uploaded',
  productLink: 'Product Link',
};
